apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: auth
  name: auth-deployment
  labels:
    istio-injection: enabled
    app: auth
spec:
  replicas: 2  # Number of replicas
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: auth
      containers:
      - name: auth
        image: ghcr.io/yousofmersal/auth:latest 
        ports:
        - containerPort: 7070
        env:
          - name: DATABASE_URL
            valuefrom:
              secretKeyRef:
                name: db-secret
                key: DATABASE_URL
          - name: SERVER_IP
            value: "0.0.0.0"
          - name: CLIENT_ID
            valuefrom:
              secretKeyRef:
                name: client-id-secret
                key: CLIENT_ID
          - name: CLIENT_SECRET
            valuefrom:
              secretKeyRef:
                name: client-secret-secret
                key: CLIENT_SECRET
      imagePullSecrets:
        - name: dockerconfigjson-github-com
