apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auth
spec:
  selector:
    app: auth
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 7070
    - name: https
      protocol: TCP
      port: 443
      targetPort: 7070
