apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: auth-virtual-service
  namespace: istio-system
spec:
  hosts:
  - milesstorm.com
  gateways:
  - public-gateway
  http: []
