apiVersion: argoproj.io/v1alpha1
kind: Application
project: default
metadata:
  name: website
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/yousofmersal/frontend:latest 
source:
  repoURL: 'git@github.com:YousofMersal/website.git'
  path: crds/frontend
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
  namespace: frontend
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
