apiVersion: batch/v1
kind: Job
metadata:
  name: frontend-cloudflare-cache
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: cloudflare-cache-hook
          image: curlimages/curl
          command:
            - "curl"
            - "--request"
            - "POST"
            - "--url"
            - "--header"
            - 'Content-Type: application/json'
            - "--header"
            - "--header"
            - "--data"
            - '{"purge_everything":true}'
      restartPolicy: Never
  backoffLimit: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: frontend
  name: frontend-deployment
  labels:
    istio-injection: enabled
    app: frontend
spec:
  replicas: 1  # Number of replicas
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/yousofmersal/frontend:latest 
        ports:
        - containerPort: 80  # Exposing internal port 80
      imagePullSecrets:
        - name: dockerconfigjson-github-com
