apiVersion: batch/v1
kind: Job
metadata:
  name: frontend-cloudflare-cache
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    metedata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: cloudflare-cache-hook
          image: curlimages/curl
          command:
              - "sh"
              - "-c"
              - |
               curl -4 -v --request POST \
                   --url "$CLOUDFLARE_URL" \
                   --header "Content-Type: application/json" \
                   --header "X-Auth-Email: $CLOUDFLARE_EMAIL" \
                   --header "X-Auth-Key: $CLOUDFLARE_TOKEN" \
                   --data '{"purge_everything":true}'
          env:
            - name: CLOUDFLARE_URL
              valueFrom:
                secretKeyRef:
                  name: cloudflare-secrets
                  key: url
            - name: CLOUDFLARE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-secrets
                  key: token
            - name: CLOUDFLARE_EMAIL
              valueFrom:
                secretKeyRef:
                  name: cloudflare-secrets
                  key: email
      restartPolicy: Never
  backoffLimit: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: frontend
  name: frontend-deployment
  labels:
    istio-injection: enabled
    app: frontend
spec:
  replicas: 1  # Number of replicas
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/yousofmersal/frontend:latest 
        ports:
        - containerPort: 80  # Exposing internal port 80
      imagePullSecrets:
        - name: dockerconfigjson-github-com
