apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: frontend-gateway
  namespace: frontend
annotations:
  # cert-manager.io/cluster-issuer: letsencrypt-prod  # Use Let's Encrypt production issuer
  # kubernetes.io/tls-acme: "true"  # Enable ACME for TLS certificates
spec:
  selector:
    istio: ingressgateway  # use Istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      # tls:
      #   mode: SIMPLE  # TLS termination at the gateway
      #   credentialName: "letsencrypt-prod"  # Kubernetes secret with TLS certificate
      hosts:
        - "yousofmersal.com"
    # - port:
    #     number: 80
    #     name: http
    #     protocol: HTTP
    #   tls:
    #     httpsRedirect: true  # Redirect HTTP to HTTPS
      # hosts:
      #   - yousofmersal.com
