apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: frontend-virtual-service
  namespace: frontend
spec:
  hosts:
  - yousofmersal.com
  gateways:
  - istio-ingress/frontend-gateway  # Name of your gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: frontend-service.frontend.svc.cluster.local  # Name of your service
        port:
          number: 443
