apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: frontend-virtual-service
  namespace: frontend
spec:
  hosts:
  - "*"
  gateways:
  - frontend-gateway  # Name of your gateway
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: frontend-service  # Name of your service
        port:
          number: 80
