[package]
name = "frontend"
version = "0.1.2"
authors = ["yousof"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

dioxus = { version = "0.6.3", features = ["web", "router"] }

# Debug
log = "0.4.26"
dioxus-logger = "0.6.2"
console_error_panic_hook = "0.1.7"
gloo= "0.11.0"
manganis = { version = "0.6.2", features = ["dioxus"] }
dioxus-sdk = { version = "0.6.0", features = ["storage", "system_theme"] }
web-sys = {version = "0.3.77", features = ['Navigator',
  'MediaDevices',
  'GetUserMediaRequest',
  'MediaStream',
  'MediaStreamConstraints',
  'CanvasRenderingContext2d',
  'HtmlCanvasElement',
  'HtmlMediaElement',
  'HtmlVideoElement',
  'ImageData',
  'HtmlElement',
  'ContextAttributes2d',
  'Element']}
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
tracing = { version = "0.1.41", features = ["log"] }
reqwest = { version = "0.12.12", features = ["json", "cookies"] }
wasm-bindgen-futures = "0.4.50"
anyhow = "1.0.96"

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
# nokhwa = { version = "0.10.4", features = ["input-jscam"] }
