name: auth-build

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches:
      - main
    paths: 
    - services/auth/**
    - .github/workflows/auth.yml
  workflow_dispatch:

jobs:
  build:    
    permissions:
      contents: read
      packages: write
    name: Build
    runs-on: self-hosted
    steps:
      - name: check out repo code
        uses: actions/checkout@v4
        
      - name: Crate Version
        id: crate-version
        uses: colathro/crate-version@1.0.0
        with:
          file: "services/auth/Cargo.toml"
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/milesstorm/auth
          tags: | 
            type=raw,value=latest
            type=sha
            type=semver,pattern={{version}},value=${{ steps.crate-version.outputs.version }}

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false

      - name: build and push
        uses: docker/build-push-action@v5
        with: 
          context: services/auth
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
