name: site-build

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches:
      - main
    paths: 
    - services/frontend/**
    - .github/workflows/frontend.yml

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: check out repo code
        uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/yousofmersal/website
          tags: | 
            type=raw,value=latest
            type=sha

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false

      - name: build and push
        uses: docker/build-push-action@v3
        with: 
          context: ./services/frontend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
