name: site-build

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted
    steps:
      - name: "Dioxus Deploy"
        uses: DioxusLabs/deploy-action@0025333337468cee2a224f2db60b6434ef9e2164
        with:
          rootPath: "services/frontend"
          
